/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.33.0-g88a52d5 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.33.0-g88a52d5"
#endif
#define SDL_REVISION_NUMBER 0
